name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

# This pipeline is inspired by the template 
# https://github.com/statisticsnorway/azure-pipelines-templates/blob/master/javascript/react-complete-build.yml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: appName
    value: 'bip-start'
  - name: imageTag
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
  - name: teamname
    value: 'stratus'
  - name: sonarQubeServiceConnection
    value: 'bipSonarQube'
  - name: gcrServiceConnection
    value: 'gcrServiceConnection'
  - name: REACT_APP_BE_GENERATE
    value: 'https://bip-start.staging-bip-app.ssb.no/be/bip-initializer/api/v1/generate'


jobs:
  - job: pullRequestOrMaster
    displayName: 'Test, build, report test coverage, build & push Docker image, scan for vulns & retag image'
    steps:
      - script: |
          set -e
          yarn
          CI=true yarn coverage
          CI=true yarn build
        displayName: 'Tests and build'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage results'
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

      - task: SonarQubePrepare@4
        displayName: 'SonarQube prepare (unless PR)'
        # For now, SonarQube can only be used on 'master' branch and hence cannot be run on PRs. 
        # Therefore, we run it on merge to master. (Yes, a bit too late, but better than nothing.)
        # This condition combined with the "master branch" trigger for the pipeline, should ensure that
        # this task only runs for the master branch
        condition: ne(variables['Build.Reason'], 'PullRequest')
        inputs:
          SonarQube: '$(sonarQubeServiceConnection)'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: $(Build.DefinitionName)
          cliProjectName: $(Build.Repository.Name)
          cliSources: '.'
      - task: SonarQubeAnalyze@4
        displayName: 'SonarQube analyze (unless PR)'
        condition: ne(variables['Build.Reason'], 'PullRequest')
      - task: SonarQubePublish@4
        displayName: 'SonarQube publish (unless PR)'
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          repository: 'eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName)'
          command: 'build'
          Dockerfile: 'Dockerfile'
          tags: 'imagescan-$(imageTag)'
      - task: Docker@2
        displayName: 'Docker Login'
        inputs:
          command: 'login'
          containerRegistry: '$(gcrServiceConnection)'
      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          repository: 'prod-bip/ssb/$(teamname)/$(appName)'
          command: 'push'
          containerRegistry: '$(gcrServiceConnection)'
          tags: 'imagescan-$(imageTag)'
      - task: DownloadSecureFile@1
        displayName: 'Download GCR key'
        name: gcrJsonKey
        inputs:
          secureFile: 'gcr-key.json'
      - script: |
          echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(gcrJsonKey.secureFilePath)"
        displayName: 'Set GCR Key'
      - task: gcr-vulneralbility-check@1
        displayName: 'GCR image vuln check'
        inputs:
          projectId: 'prod-bip'
          imageHost: 'https://eu.gcr.io/'
          image: 'prod-bip/ssb/$(teamname)/$(appName)'
          imageTag: 'imagescan-$(imageTag)'
          timeBetweenRetries: '10000'
      - script: |
          set -e
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin https://eu.gcr.io/
          docker tag eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):imagescan-$(imageTag) eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):$(imageTag)
          docker tag eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):imagescan-$(imageTag) eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):latest
          docker push -a eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName)
        displayName: 'Retag image after vuln check'
        condition: succeeded()
