name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - main
        stratus-731_add-pipeline

pr:
  branches:
    include:
      - main
        stratus-731_add-pipeline

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: 'appName'
    value: 'bip-start'
  - name: imageHost
    value: 'https://eu.gcr.io/'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/stratus/platform-demo-app'
  - name: repoName
    value: 'prod-bip/ssb/stratus/platform-demo-app'
  - name: imageTagBeforeVulnerabilityScan
    value: 'imagescan-$(Build.SourceBranchName)-$(fullSha)'
  - name: imageTagAfterVulnerabilityScan
    value: $(Build.SourceBranchName)-$(fullSha)
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.18
      endpoint: github

jobs:
  - template: javascript/react-complete-build.yml@templates
    parameters:
      appName: $(appName)
      imageTag: $(imageTag)

  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'master-$(fullSha)'
      gcrImageName: $(imageName)
