name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      # Locking to version/tag 1.1.22, update as new version tags for the repo are created 
      ref: refs/tags/1.1.22
      # endpoint: Name of service connection in team project in Az Pipelines
      endpoint: github

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: javascript/react-complete-build.yml@templates
    # This template contains jobs for building code, building code + creating Docker image, and for tagging Docker image for production
    # Ref. https://github.com/statisticsnorway/azure-pipelines-templates/blob/master/javascript/react-complete-build.yml 
    parameters:
      # appName is used to construct the path/name for the created Docker image
      appName: 'bip-start'
      # imageTag is used to tag the created Docker image: 'imagescan-${{ parameters.imageTag }}'
      imageTag: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
      # namespace is used to construct the path for the created Docker image: 'prod-bip/ssb/${{ parameters.namespace }}/${{ parameters.appName }}'
      namespace: 'stratus'
      # tagToTag is used in conjunction with masterBranch to fetch & tag correct image when "tagging for prod"
      tagToTag: '$(Build.SourceVersion)'
      # masterBranch is used in conjunction with tagToTag to fetch & tag correct image when "tagging for prod"
      masterBranch: 'main'
