name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

# This pipeline is inspired by the template 
# https://github.com/statisticsnorway/azure-pipelines-templates/blob/master/javascript/react-complete-build.yml

trigger:
  branches:
    include:
      - master
      - STRATUS-731_separate_pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: appName
    value: 'bip-start'
  - name: imageTag
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
  - name: teamname
    value: 'stratus'
  - name: sonarQubeServiceConnection
    value: 'bipSonarQube'
  - name: gcrServiceConnection
    value: 'gcrServiceConnection'

jobs:
  - job: pullRequest
    displayName: 'Analyze code and build and push Docker image'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    steps:
      - script: |
          set -e
          yarn
          CI=true yarn coverage
          CI=true yarn build
        displayName: 'Tests and build'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
#      - task: SonarQubePrepare@4
#        inputs:
#          SonarQube: '$(sonarQubeServiceConnection)'
#          scannerMode: 'CLI'
#          configMode: 'manual'
#          cliProjectKey: $(Build.DefinitionName)
#          cliProjectName: $(Build.Repository.Name)
#          cliSources: '.'
#      - task: SonarQubeAnalyze@4
#      - task: SonarQubePublish@4
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          repository: 'eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName)'
          command: 'build'
          Dockerfile: 'Dockerfile'
          tags: 'imagescan-$(imageTag)'
      - task: Docker@2
        displayName: 'Docker Login'
        inputs:
          command: 'login'
          containerRegistry: '$(gcrServiceConnection)'
      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          repository: 'prod-bip/ssb/$(teamname)/$(appName)'
          command: 'push'
          containerRegistry: '$(gcrServiceConnection)'
          tags: 'imagescan-$(imageTag)'
      - task: DownloadSecureFile@1
        name: gcrJsonKey
        inputs:
          secureFile: 'gcr-key.json'
      - script: |
          echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(gcrJsonKey.secureFilePath)"
        displayName: 'Set GCR Key'
      - task: gcr-vulneralbility-check@1
        inputs:
          projectId: 'prod-bip'
          imageHost: 'https://eu.gcr.io/'
          image: 'prod-bip/ssb/$(teamname)/$(appName)'
          imageTag: 'imagescan-$(imageTag)'
          timeBetweenRetries: '10000'
      - script: |
          set -e
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin https://eu.gcr.io/
          docker tag eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):imagescan-$(imageTag) eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):$(imageTag)
          docker tag eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):imagescan-$(imageTag) eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName):latest
          docker push -a eu.gcr.io/prod-bip/ssb/$(teamname)/$(appName)
        displayName: 'Retag image after vuln scan'
        condition: succeeded()
